# Generated by Django 3.2.4 on 2021-07-19 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_studentgroupassignment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentgroupassignment',
            options={'ordering': ['student__last_name', 'student__first_name', 'date_start'], 'verbose_name': 'Group assignment', 'verbose_name_plural': 'Group assignments'},
        ),
    ]
