# Generated by Django 3.2.4 on 2021-07-21 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_alter_course_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['date_start'], 'verbose_name': 'Schedule entry', 'verbose_name_plural': 'Schedule entries'},
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Planned'), (1, 'Realized')], default=0, verbose_name='Status')),
                ('date', models.DateField(verbose_name='Date')),
                ('subject', models.TextField(blank=True, verbose_name='Subject')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='records.schedule', verbose_name='Schedule entry')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lesson',
                'ordering': ['date'],
                'unique_together': {('schedule', 'date')},
            },
        ),
    ]
