# Generated by Django 3.2.4 on 2021-07-25 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_auto_20210724_2045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-lesson__date', 'student__last_name', 'student__first_name'], 'verbose_name': 'Attendance', 'verbose_name_plural': 'Attendances'},
        ),
        migrations.AlterField(
            model_name='lesson',
            name='subject',
            field=models.CharField(blank=True, max_length=255, verbose_name='Subject'),
        ),
    ]
