# Generated by Django 3.2.4 on 2021-08-02 16:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_auto_20210725_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required. 3 - 60 characters.', max_length=60, unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required. 1 - 5 characters.', max_length=5, verbose_name='Name')),
                ('value', models.DecimalField(decimal_places=2, help_text='Required. From 0 to 9.99.', max_digits=3, verbose_name='Value')),
            ],
            options={
                'verbose_name': 'Symbol',
                'verbose_name_plural': 'Symbols',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.IntegerField(choices=[(0, 'Unrealized'), (1, 'Realized'), (2, 'Cancelled')], default=0, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Required', on_delete=django.db.models.deletion.PROTECT, to='records.category')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marks', to='records.course')),
                ('student', models.ForeignKey(limit_choices_to={'is_teacher': False}, on_delete=django.db.models.deletion.PROTECT, related_name='marks', to=settings.AUTH_USER_MODEL)),
                ('symbol', models.ForeignKey(help_text='Required', on_delete=django.db.models.deletion.PROTECT, to='records.symbol')),
                ('teacher', models.ForeignKey(limit_choices_to={'is_teacher': True}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mark',
                'verbose_name_plural': 'Marks',
                'ordering': ['student__last_name', 'student__first_name', 'date_created'],
            },
        ),
        migrations.CreateModel(
            name='ChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Add'), (1, 'Modify'), (2, 'Erase')], verbose_name='Type')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.mark')),
                ('user', models.ForeignKey(limit_choices_to={'is_teacher': True}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('value_new', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='records.symbol', verbose_name='New value')),
                ('value_old', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='records.symbol', verbose_name='Old value')),
            ],
            options={
                'verbose_name': 'Mark change history',
                'verbose_name_plural': 'Mark change history',
                'ordering': ['-timestamp'],
            },
        ),
    ]
