# Generated by Django 3.2.4 on 2021-08-08 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_auto_20210802_1635'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='symbol',
            options={'ordering': ['value'], 'verbose_name': 'Symbol', 'verbose_name_plural': 'Symbols'},
        ),
        migrations.AlterField(
            model_name='mark',
            name='student',
            field=models.ForeignKey(help_text='Required', limit_choices_to={'is_teacher': False}, on_delete=django.db.models.deletion.PROTECT, related_name='marks', to=settings.AUTH_USER_MODEL),
        ),
    ]
